Document: bomberclone
Title: Debian bomberclone Manual
Author: <insert document author here>
Abstract: This manual describes what bomberclone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bomberclone/bomberclone.sgml.gz

Format: postscript
Files: /usr/share/doc/bomberclone/bomberclone.ps.gz

Format: text
Files: /usr/share/doc/bomberclone/bomberclone.text.gz

Format: HTML
Index: /usr/share/doc/bomberclone/html/index.html
Files: /usr/share/doc/bomberclone/html/*.html

  
